// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGTeQdL8ogukM1DQGFexaqqqJ80Kr_Qng',
    appId: '1:887461055219:web:c041ebad6c94ba323c0586',
    messagingSenderId: '887461055219',
    projectId: 'mydatingapp-99dbe',
    authDomain: 'mydatingapp-99dbe.firebaseapp.com',
    storageBucket: 'mydatingapp-99dbe.appspot.com',
    measurementId: 'G-Y8DTCNPK7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_dSsoF_oRXFB__wtHqwjxsAW4PBwKSTo',
    appId: '1:887461055219:android:546c1161702a617e3c0586',
    messagingSenderId: '887461055219',
    projectId: 'mydatingapp-99dbe',
    storageBucket: 'mydatingapp-99dbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6EYEtpwTz7JbSNGgc3n98NpggoPt623E',
    appId: '1:887461055219:ios:796e83eec1d74a6e3c0586',
    messagingSenderId: '887461055219',
    projectId: 'mydatingapp-99dbe',
    storageBucket: 'mydatingapp-99dbe.appspot.com',
    iosClientId: '887461055219-h52pu7v5ckep069iq7v5b359943hu11c.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6EYEtpwTz7JbSNGgc3n98NpggoPt623E',
    appId: '1:887461055219:ios:796e83eec1d74a6e3c0586',
    messagingSenderId: '887461055219',
    projectId: 'mydatingapp-99dbe',
    storageBucket: 'mydatingapp-99dbe.appspot.com',
    iosClientId: '887461055219-h52pu7v5ckep069iq7v5b359943hu11c.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingapp',
  );
}
